// SPDX-License-Identifier: GPL-2.0-only

package ccx

import (
	"bufio"
	"fmt"
	"io"
)

// deckBuf is a line-oriented writer for the CalculiX .inp deck that captures the first
// write error so the section writers stay free of repetitive error plumbing.
type deckBuf struct {
	bw  *bufio.Writer
	err error
}

func newDeckBuf(w io.Writer) *deckBuf { return &deckBuf{bw: bufio.NewWriter(w)} }

// line writes one formatted deck line (a trailing newline is added).
func (d *deckBuf) line(format string, a ...any) {
	if d.err != nil {
		return
	}
	if _, err := fmt.Fprintf(d.bw, format+"\n", a...); err != nil {
		d.err = err
	}
}

func (d *deckBuf) flush() error {
	if d.err != nil {
		return d.err
	}
	return d.bw.Flush()
}

// WriteDeck writes the full CalculiX input deck for the model in the canonical section
// order: mesh, material, section, constraint sets, *STEP, step-dependent loads/BCs,
// output requests, *END STEP. Adding a constraint kind is a new ConstraintWriter in the
// registry, not an edit here.
func WriteDeck(w io.Writer, m *AnalysisModel) error {
	d := newDeckBuf(w)
	writeUnitsBanner(d)
	writeMesh(d, m.Mesh)
	writeMaterial(d, m.Material, m.needsDensity())
	writeSolidSection(d, m.Material.Name)

	cons := constraintWriters(m)
	for _, c := range cons {
		c.WriteSets(d)
	}
	writeStepBegin(d, m.Analysis, m.EigenmodeCount)
	for _, c := range cons {
		c.WriteStep(d)
	}
	writeStepOutput(d, m.Analysis)
	writeStepEnd(d)
	return d.flush()
}

// writeUnitsBanner records the unit convention the deck is written in, so a reader (or a
// future result import) is never left guessing. CalculiX is unit-agnostic; the add-in
// fixes mm / t / s -> N, MPa (see units.go).
func writeUnitsBanner(d *deckBuf) {
	d.line("** Generated by the Oblikovati CalculiX add-in.")
	d.line("** Units: length mm, mass t, time s -> force N, stress MPa, density t/mm^3.")
}
